config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    resources :carts do
      collection do
        post "create/:id", to: "carts#create", as: "add_to"
        post "increase/:id", to: "carts#increase", as: "increase"
        post "descrease/:id", to: "carts#descrease", as: "descrease"
        post "remove/:id", to: "carts#remove", as: "remove_item_from"
        post "update/:id", to: "carts#update", as: "update"
        get :show
        delete :destroy, as: "clear"
      end
    end
    resources :orders, except: [:update, :edit, :destroy] do
        collection do
            post "cancel/:id", to: "orders#cancel", as: "cancel"
        end
    end
    resources :categories, only: [:show, :index]
    resources :products, only: [:show, :index]
    namespace :admin do
        resources :orders, only: :index do
            post "next_status", to: "orders#next_status"
        end
    end
    devise_for :users
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :user

  enum status: {
    waiting: 0,
    approved: 1,
    delivering: 2,
    delivered: 3,
    canceled: 4
  }

  scope :latest, ->{order(created_at: :desc)}
  scope :group_by_status, ->(status){where("status = ?", status)}

  def add_order_items cart, total
    cart.each do |k, v|
      item = order_items.build product_id: k,
                                    quantity: v
      item.save!
      product = Product.find_by! id: k
      product.update! quantity: product.quantity - v
    end
    update! total: total
  end

  def cancel_order
    raise StandardException if order_items.empty?

    order_items.each do |item|
      product = Product.find_by! id: item.product_id
      product.update! quantity: product.quantity + item.quantity
    end
    canceled!
  end

  validates :address, presence: true
  validates :name, presence: true
  validates :phone, format: {with: Settings.order.address.regex}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :load_order, only: :next_status
  authorize_resource

  include Admin::OrdersHelper
  def index
    @orders = Order.latest.paginate(page: params[:page])
    authorize! :index, @orders
  end

  def next_status
    if status_for_next @order
      case @order.status
      when "waiting"
        @order.approved!
      when "approved"
        @order.delivering!
      when "delivering"
        @order.delivered!
      end
      flash[:success] = t "order.next_success"
      redirect_to @order
    else
      flash[:danger] = t "order.wrong_status"
      redirect_to admin_orders_path
    end
  rescue StandardError
    flash[:danger] = t "index.error"
    redirect_to admin_orders_path
  end

  private

  def load_order
    @order = Order.find_by id: params[:order_id]
    return if @order

    flash[:danger] = t "order.nil"
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :check_cart, :load_products,
                :handle_total, only: [:new, :create]
  before_action :load_order, only: [:show, :cancel]
  before_action :check_cancel_status, only: :cancel

  include OrdersHelper
  def new
    @order = Order.new
  end

  def create
    handle_create
    if flash[:success]
      session[:cart] = {}
      redirect_to @order
    else
      render :new
    end
  end

  def show; end

  def index
    @orders = current_user.orders.latest
    if params[:status].present?
      @orders = @orders.group_by_status(params[:status])
    end
    @orders = @orders.paginate(page: params[:page])
  end

  def cancel
    handle_cancel
    if flash[:success]
      redirect_to @order
    else
      render :new
    end
  end

  private

  def load_products
    @products = Product.load_cart(session[:cart].keys)
  end

  def order_params
    params.require(:order).permit(:name, :address, :phone)
  end

  def handle_create
    ActiveRecord::Base.transaction do
      @order = current_user.orders.build order_params
      @order.save!
      @order.add_order_items session[:cart], @totals
      flash[:success] = t "order.success"
    rescue StandardError
      flash[:danger] = t "index.error"
      raise ActiveRecord::Rollback
    end
  end

  def handle_cancel
    ActiveRecord::Base.transaction do
      @order.cancel_order
      flash[:success] = t "order.cancel_success"
    rescue StandardError
      flash[:danger] = t "index.error"
      raise ActiveRecord::Rollback
    end
  end

  def check_cart
    return unless session[:cart] == {} || session[:cart].nil?

    flash[:danger] = t "cart.nothing"
    redirect_to root_path
  end

  def handle_total
    @totals = @products.reduce(0) do |sum, p|
      sum + session[:cart][p.id.to_s] * p.price
    end
  end

  def load_order
    authorize! :manage, @order
    return if @order

    flash[:danger] = t "order.nil"
    redirect_to root_path
  end

  def check_cancel_status
    return if status_for_cancel @order

    flash[:danger] = t "order.wrong_status"
    redirect_to @order
  end

  def check_order_owner
    return if check_authorize @order

    flash[:danger] = "t.not_order_owner"
    redirect_to root_path
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def status_for_next order
    !(order.canceled? || order.delivered?)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def status_for_cancel order
    order.waiting? || order.delivering?
  end

  def check_authorize order
    order.user == current_user || current_user.admin?
  end
end

app/views/orders/index.html.erb
<% provide :title, t("order.your") %>
<h1><%= t "order.your"%>(<%=@orders.count %>)</h1>
<div class="row">
  <%= form_tag("/orders", method: :get) do %>
    <div class="col-lg-4">
      <%= label_tag(:status, t("status.select")) %>
      <%= select_tag :status, options_for_select(Order.statuses.map {|k, v| [k.capitalize, v]}), include_blank: t("status.all")%>
    </div>
    <div class="col-lg-3">
      <%= label_tag %>
      <%= submit_tag t("status.select") %>
    </div>
  <% end %>
</div>
<div class="container">
  <ul class="list-group">
    <%= render @orders %>
  </ul>
  <%= will_paginate @orders%>
</div>

app/views/orders/new.html.erb
<% provide :title, t("order.new") %>
<h1><%= t "order.new" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @order, url: orders_path do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name , t("order.name") %>
      <%= f.text_field :name %>
      <%= f.label :address, t("order.address") %>
      <%= f.text_field :address %>
      <%= f.label :phone, t("order.phone") %>
      <%= f.text_field :phone %>
      <% if @products.any? %>
        <table width="100%" id ="cart">
          <tr>
            <td><%= t "product.image" %></td>
            <td><%= t "product.name" %></td>
            <td><%= t "product.price" %></td>
            <td><%= t "product.quantity" %></td>
            <td><%= t "product.total_price" %></td>
          </tr>
          <% @products.each do |product| %>
          <tr class="cart_item">
            <td class="image">
              <%= image_tag "https://media.gettyimages.com/photos/different-types-of-food-on-rustic-wooden-table-picture-id861188910?s=612x612", size: Settings.image.minisize %>
            </td>
            <td class="name">
              <span><%= product.name %></span>
            </td>
            <td class="price">
              <span><%= number_to_currency(product.price, unit: t("index.currency")) %></span>
            </td>
            <td class="cart_quantity" >
              <span><%= session[:cart]["#{product.id}"] %></span>
            </td>
            <td class="total_price">
              <%= number_to_currency((session[:cart]["#{product.id}"] * product.price), unit: t("index.currency")) %>
            </td>
          </tr>
          <% end %>
        </table>
        <h2 align="right">
          <%= t("cart.total") %><%= number_to_currency(@totals.round(2), unit: t("index.currency")) %>
        </h2>
      <% else %>
        <h1 align="center"><%= t "cart.nothing" %></h1>
        <p align="center"><%= link_to t("index.buy_now"), root_path %>
      <% end %>
      <%= f.submit t("order.checkout"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<% provide :title, t("order.your") %>
<h1><%= t "order.your" %></h1>
<p><label><%= t "order.time" %>: <%= @order.created_at %></label></p>
<p><label><%= t "order.name" %>: <%= @order.name %></label></p>
<p><label><%= t "order.address" %>: <%= @order.address %></label></p>
<p><label><%= t "order.phone" %>: <%= @order.phone %></label></p>
<p><label><%= t "order.status" %>: <%= @order.status %></label></p>

<table width="100%">
  <% @order.order_items.each do |item| %>
    <tr>
      <td><%= item.product.name %></td>
      <td><%= item.quantity %></td>
      <td><%= number_to_currency(item.product.price, unit: t("index.currency")) %></td>
    </tr>
  <% end %>
</table>
<h1 align="right"><label><%= t "order.total" %>: <%= number_to_currency(@order.total, unit: t("index.currency")) %></h1>
<% if check_authorize @order %>
  <h1 align="right">
    <%= link_to t("order.cancel"), cancel_orders_path(@order.id), method: :post %>
  </h1>
<% end %>
<% if current_user.admin? %>
  <h1 align="right">
    <%= link_to t("order.next_status"), admin_order_next_status_path(@order.id), method: :post %>
  </h1>
<% end %>