config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    resources :carts do
      collection do
        post "create/:id", to: "carts#create", as: "add_to"
        post "increase/:id", to: "carts#increase", as: "increase"
        post "descrease/:id", to: "carts#descrease", as: "descrease"
        post "remove/:id", to: "carts#remove", as: "remove_item_from"
        post "update/:id", to: "carts#update", as: "update"
        get :show
        delete :destroy, as: "clear"
      end
    end
    resources :orders, except: [:update, :edit, :destroy] do
        collection do
            post "cancel/:id", to: "orders#cancel", as: "cancel"
        end
    end
    resources :categories, only: [:show, :index]
    resources :products, only: [:show, :index]
    namespace :admin do
        resources :orders, only: :index do
            post "next_status", to: "orders#next_status"
        end
    end
    devise_for :users
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, :init_cart
  before_action :load_product, except: [:show, :destroy]
  before_action :handle_cart, only: :show
  before_action :check_quantity, only: :update
  before_action :empty_cart?, only: :destroy

  def create
    flash[:success] = t("cart.add_item", name: @product.name)
    handle_quantity
    redirect_to root_path
  end

  def show
    @products = Product.load_cart(session[:cart].keys)
                       .paginate(page: params[:page])
    @totals = @products.reduce(0) do |sum, p|
      sum + session[:cart][p.id.to_s] * p.price
    end
  end

  def remove
    delete_cart_item @product.id
    flash[:success] = t("cart.item_removed", name: @product.name)
    redirect_to cart_path
  end

  def destroy
    session[:cart] = {}
    flash[:success] = t "cart.cleared"
    redirect_to carts_path
  end

  def increase
    if session[:cart][@product.id.to_s] == @product.quantity
      flash.now[:danger] = t "cart.over"
    else
      session[:cart][@product.id.to_s] += 1
    end
    respond_to do |format|
      format.html{redirect_to carts_path}
      format.js
    end
  end

  def descrease
    if session[:cart][@product.id.to_s] == 1
      delete_cart_item @product.id
    else
      session[:cart][@product.id.to_s] -= 1
    end
    respond_to do |format|
      format.html{redirect_to carts_path}
      format.js
    end
  end

  def update
    session[:cart][@product.id.to_s] = params[:session][:quantity].to_i
    respond_to do |format|
      format.html{redirect_to carts_path}
      format.js
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "product.nil"
    redirect_to products_path
  end

  def handle_quantity
    if session[:cart].include? @product.id.to_s
      session[:cart][@product.id.to_s] += 1
    else
      session[:cart][@product.id.to_s] = 1
    end
  end

  def must_login
    return if logged_in?

    flash[:danger] = t "cart.must_login"
    redirect_to login_path
  end

  def handle_cart
    session[:cart].each do |id|
      break if Product.find_by id: id

      delete_cart_item id
    end
  end

  def delete_cart_item id
    session[:cart].delete(id.to_s)
  end

  def empty_cart?
    return unless session[:cart] == {}

    flash[:danger] = t "cart.empty"
    redirect_to carts_path
  end

  def check_quantity
    return if params[:session][:quantity].to_i < @product.quantity &&
              params[:session][:quantity].to_i.positive?

    session[:cart][@product.id.to_s] = 1
    flash[:danger] = t "cart.over"
    redirect_to carts_path
  end

  def init_cart
    session[:cart] ||= {}
  end
end

app/views/carts/descrease.js.erb
$('#cart').html('<%= j render :show %>')
$('#cart_quantity').html('<%= session[:cart]["#{product.id}"] %>')

app/views/carts/increase.js.erb
$('#cart').html('<%= j render :show %>')
$('#cart_quantity').html('<%= session[:cart]["#{product.id}"] %>')

app/views/carts/show.html.erb
<% provide :title, t("cart.your") %>
<h1><%= t"cart.your"%> (<%= @products.count %>)</h1>
<p><%= link_to t("cart.clear"), clear_carts_path, method: :delete %></p>
<% if @products.any? %>
  <table width="100%" id ="cart">
    <tr>
      <td><%= t "product.image" %></td>
      <td><%= t "product.name" %></td>
      <td><%= t "product.in_stock" %></td>
      <td><%= t "product.price" %></td>
      <td><%= t "product.quantity" %></td>
      <td><%= t "product.total_price" %></td>

    </tr>
    <% @products.each do |product| %>
    <tr class="cart_item">
      <td class="image">
        <%= image_tag "https://media.gettyimages.com/photos/different-types-of-food-on-rustic-wooden-table-picture-id861188910?s=612x612", size: Settings.image.minisize %>
      </td>
      <td class="name">
        <span><%= product.name %></span>
      </td>
      <td class="name">
        <span><%= product.quantity %></span>
      </td>
      <td class="price">
        <span><%= number_to_currency(product.price, unit: t("index.currency")) %></span>
      </td>
      <td class="cart_quantity" >
        <strong data-remote="true"><%=link_to "+", increase_carts_path(product.id), method: :post %></strong>
        <span id="cart_quantity">
          <%= form_for :session, url: update_carts_path(product.id) do |f| %>
            <%= f.number_field :quantity, value: session[:cart]["#{product.id}"] %>
            <%= f.submit t("index.update"), class: "btn btn-primary" %>
          <% end %>
        </span>
        <strong data-remote="true"><%=link_to "-", descrease_carts_path(product.id), method: :post %></strong>
      </td>
      <td class="total_price">
        <%= number_to_currency((session[:cart]["#{product.id}"] * product.price), unit: t("index.currency")) %>
      </td>
      <td>
        <%= link_to t("cart.remove"), remove_item_from_carts_path(product.id), method: :post %>
      </td>
    </tr>
    <% end %>
  </table>
  <h2 align="right">
    <%= t("cart.total") %><%= number_to_currency(@totals.round(2), unit: t("index.currency")) %>
  </h2>
  <h1 align="right">
    <%= link_to t("index.order"), new_order_path %>
  </h1>
<% else %>
  <h1 align="center"><%= t "cart.nothing" %></h1>
  <p align="center"><%= link_to t("index.buy_now"), root_path %>
<% end %>
<%= will_paginate @products,
  params: { controller: :carts, action: :show } %>

app/views/carts/update.js.erb
$('#cart').html('<%= j render :show %>')
$('#cart_quantity').html('<%= session[:cart]["#{product.id}"] %>')