config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    resources :carts do
      collection do
        post "create/:id", to: "carts#create", as: "add_to"
        post "increase/:id", to: "carts#increase", as: "increase"
        post "descrease/:id", to: "carts#descrease", as: "descrease"
        post "remove/:id", to: "carts#remove", as: "remove_item_from"
        post "update/:id", to: "carts#update", as: "update"
        get :show
        delete :destroy, as: "clear"
      end
    end
    resources :orders, except: [:update, :edit, :destroy] do
        collection do
            post "cancel/:id", to: "orders#cancel", as: "cancel"
        end
    end
    resources :categories, only: [:show, :index]
    resources :products, only: [:show, :index]
    namespace :admin do
        resources :orders, only: :index do
            post "next_status", to: "orders#next_status"
        end
    end
    devise_for :users
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items, dependent: :destroy
  has_many :ratings, dependent: :destroy
  belongs_to :category

  scope :asc_name, ->{order :name}
  scope :load_cart, ->(product_ids){where(id: product_ids)}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :init_q, only: :index
  def show
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "product.nil"
    redirect_to products_path
  end

  def index
    @q = if params[:q][:category_id]
           Product.ransack(params[:q][:category_id])
         else
           Product.ransack(params[:q])
         end
    @catgories = Category.select(:id, :name)
    @products = @q.result.paginate(page: params[:page])
  end

  private

  def init_q
    params[:q] ||= {}
  end
end

app/views/products/_filter_form.html.erb
<div class="container">
  <%= search_form_for @q do |f| %>
    <div class="col-lg-3">
      <%= f.label :name_or_description_cont %>
      <%= f.search_field :name_or_description_cont %>
    </div>
    <div class="col-lg-3">
      <%= f.label :category%>
      <%= f.select :category_id_eq, options_from_collection_for_select(@catgories, "id", "name", @q.category_id_eq),include_blank: t("category.all") %>
    </div>
    <div class="col-lg-3">
      <%= f.label ""%>
      <%= f.submit %>
    </div>
    <div class="col-lg-2">
      <%= sort_link(@q, :price, t("index.price")) %>
    </div>
  <% end %>
</div>
<% if params[:q][:name_or_description_cont].present? %>
  <h3><%= t("filter.result", name: params[:q][:name_or_description_cont]) %></h3>
<% end %>
<% if params[:q][:s].present? %>
  <% if params[:q][:s].eql? "price asc"%>
    <h3><%= t("filter.price", direction: "↑") %></h3>
  <% else %>
    <h3><%= t("filter.price", direction: "↓") %></h3>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-6 col-md-4 col-lg-3 mt-4" style="text-align: center">
  <%= link_to product do %>
    <%= image_tag "https://media.gettyimages.com/photos/different-types-of-food-on-rustic-wooden-table-picture-id861188910?s=612x612", size: Settings.image.size %>
    <p class="pl-3 mb-0" style="color:black"><%= product.name %></p>
    <b class="pl-2" style="color:black">
      <%= number_to_currency(product.price, unit: t("index.currency")) %>
    </b>
    <p id="add"><%= link_to t("cart.add"), add_to_carts_path(product.id), method: :post %></p>
  <% end %>
</div>

app/views/products/index.html.erb
<%= render "products/filter_form" %>
<div>
  <% if @products.empty? %>
    <h1><%= t "filter.not_found" %></h1>
  <% else %>
    <ul>
      <%= render @products %>
    </ul>
  <% end %>
</div>
<br>
<p><%= will_paginate @products %></p>

app/views/products/show.html.erb
<% provide :title, @product.name %>
<aside class="col-md-4">
  <section class="user_info">
    <h1>
      <%= @product.name %>
    </h1>
    <ul>
      <%= image_tag "https://media.gettyimages.com/photos/different-types-of-food-on-rustic-wooden-table-picture-id861188910?s=612x612", size: Settings.image.size %>
      <li><%= t "product.price" %>:&ensp;<%= number_to_currency(@product.price, unit: t("index.currency")) %></li>
      <li><%= t "product.quantity" %>:&ensp;<%= @product.quantity %></li>
      <li><%= t "product.description" %>:&ensp;<%= @product.description %></li>
      <li><%= link_to t("cart.add"), add_to_carts_path(@product.id), method: :post %></li>
    </ul>
  </section>
</aside>