config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "static_pages#home"
    get "static_pages/home"
    get "static_pages/help"
    resources :carts do
      collection do
        post "create/:id", to: "carts#create", as: "add_to"
        post "increase/:id", to: "carts#increase", as: "increase"
        post "descrease/:id", to: "carts#descrease", as: "descrease"
        post "remove/:id", to: "carts#remove", as: "remove_item_from"
        post "update/:id", to: "carts#update", as: "update"
        get :show
        delete :destroy, as: "clear"
      end
    end
    resources :orders, except: [:update, :edit, :destroy] do
        collection do
            post "cancel/:id", to: "orders#cancel", as: "cancel"
        end
    end
    resources :categories, only: [:show, :index]
    resources :products, only: [:show, :index]
    namespace :admin do
        resources :orders, only: :index do
            post "next_status", to: "orders#next_status"
        end
    end
    devise_for :users
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("index.title"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("index.categories"), categories_path %></li>
        <li><%= link_to t("index.home"), static_pages_home_path %></li>
        <li><%= link_to t("index.help"), static_pages_help_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to t("index.cart"), carts_path %></li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
              <%= t "index.account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("index.order"), orders_path %></li>
              <li class="divider"></li>
              <li><%= link_to t("index.logout"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% if current_user.admin? %>
          <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= t "index.admin" %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t("index.order"), admin_orders_path %></li>
          </ul>
        </li>
        <% end %>
        <% else %>
          <li><%= link_to t("index.login"), new_user_session_path %></li>
        <% end %>
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= t "index.language" %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t("index.en"), locale: :en %></li>
            <li><%= link_to t("index.vi"), locale: :vi %></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert -<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>